"""Core data structures and analyzer for cgt-availability."""

from cgt_availability.core.analyzer import AvailabilityAnalyzer
from cgt_availability.core.completion import (
    CoherentRepairProblem,
    ContinuationRepairProblem,
    DeficiencyRepairCover,
    PackagePatch,
    RepairCandidate,
    RepairCandidatePatch,
    RepairPlan,
    RepairProblem,
    greedy_repair_cover,
    solve_cascaded_repair,
    solve_coherent_repair,
    solve_continuation_repair,
    solve_repair_cover,
    solve_weighted_repair_cover,
)
from cgt_availability.core.deficiency import (
    DEFICIENCY_CODE_INFO,
    Deficiency,
    DeficiencyCode,
    DeficiencyCodeInfo,
    deficiency_code_info,
)
from cgt_availability.core.degeneracy import DirectSelectorWitness, direct_selector_witness
from cgt_availability.core.dependencies import (
    DependencyClosure,
    DependencyCondition,
    DependencyEdge,
    DependencyGraph,
    DiagnosticVocabulary,
)
from cgt_availability.core.factorization import (
    EffectProfileRecord,
    FactorizationWitness,
    find_factorization_witness,
)
from cgt_availability.core.fixed_point import (
    DeficiencyOperator,
    FixedPointResult,
    least_fixed_point,
)
from cgt_availability.core.model_checking import (
    FiniteDTMC,
    ProbabilityModelCheckResult,
    bounded_reachability_probability,
    reachability_probability,
)
from cgt_availability.core.nondeterminism import (
    RunAvailabilityReport,
    RunPackage,
    almost_sure_available,
    evaluate_run_modes,
    reproducibly_available_predicate,
)
from cgt_availability.core.package import ClaimPackage
from cgt_availability.core.pipeline import AvailabilityPipeline, PipelineLevel
from cgt_availability.core.plugins import (
    MarkerAdapter,
    ModelCheckingAdapter,
    ProvenanceStore,
    StatisticalVerifierPlugin,
)
from cgt_availability.core.preorder import availability_preorder, deficiency_profile_key
from cgt_availability.core.report import AvailabilityReport
from cgt_availability.core.residual import (
    ContinuationReadout,
    ResidualComparisonSpec,
    ResidualSimulationResult,
    ResidualTransitionSystem,
    RunMode,
    bounded_residual_simulation,
    continuation_preorder,
    continuation_preorder_result,
    continuation_readout,
    has_residual_scientific_space,
    has_residual_simulation,
    one_step_residual_labels,
    residual_includes,
    residual_refinement_count,
    residual_repair_count,
    residual_test_count,
)
from cgt_availability.core.schema import SCHEMA_VERSION, STABLE_DEFICIENCY_CODES, schema_id
from cgt_availability.core.specs import (
    ComparisonRegimeSpec,
    ContinuationSpec,
    DegeneracyControlSpec,
    DescriptionSpec,
    ExpectedReportSpec,
    FailurePredicateSpec,
    FrameSpec,
    HistorySpec,
    MarkerPolicySpec,
    MarkerStateSpec,
    NormalizerSpec,
    ObservationSpec,
    ProjectionSpec,
    ProvenanceRef,
    ReportPathSpec,
    ReproductionProtocolSpec,
    ResidualConstraintSpec,
    SystemSpec,
    TypedMapSpec,
    VerifierSpec,
)
from cgt_availability.core.statistics import (
    BernoulliEvidence,
    ConfidenceInterval,
    StatisticalVerifierResult,
    binomial_p_value,
    evaluate_binomial_verifier,
    wilson_score_interval,
)
from cgt_availability.core.status import (
    AvailabilityProfile,
    AvailabilityStatus,
    CoarseAvailabilityClass,
    coarse_availability_class,
)
from cgt_availability.core.theory import (
    TheoryAlignmentItem,
    TheoryAlignmentReport,
    TheoryImplementationStatus,
    default_theory_alignment_report,
)

__all__ = [
    "AvailabilityAnalyzer",
    "AvailabilityPipeline",
    "AvailabilityProfile",
    "AvailabilityReport",
    "AvailabilityStatus",
    "BernoulliEvidence",
    "ClaimPackage",
    "CoherentRepairProblem",
    "ConfidenceInterval",
    "ContinuationRepairProblem",
    "CoarseAvailabilityClass",
    "ComparisonRegimeSpec",
    "ContinuationSpec",
    "Deficiency",
    "DEFICIENCY_CODE_INFO",
    "DeficiencyCode",
    "DeficiencyCodeInfo",
    "DeficiencyRepairCover",
    "DegeneracyControlSpec",
    "DependencyCondition",
    "DependencyClosure",
    "DependencyEdge",
    "DependencyGraph",
    "DiagnosticVocabulary",
    "DescriptionSpec",
    "DirectSelectorWitness",
    "EffectProfileRecord",
    "ExpectedReportSpec",
    "FactorizationWitness",
    "FailurePredicateSpec",
    "DeficiencyOperator",
    "FiniteDTMC",
    "FixedPointResult",
    "FrameSpec",
    "HistorySpec",
    "MarkerAdapter",
    "MarkerPolicySpec",
    "MarkerStateSpec",
    "ModelCheckingAdapter",
    "NormalizerSpec",
    "ObservationSpec",
    "PackagePatch",
    "PipelineLevel",
    "ProjectionSpec",
    "ProbabilityModelCheckResult",
    "ProvenanceStore",
    "ProvenanceRef",
    "ReportPathSpec",
    "RepairCandidate",
    "RepairCandidatePatch",
    "RepairPlan",
    "RepairProblem",
    "ReproductionProtocolSpec",
    "ContinuationReadout",
    "ResidualComparisonSpec",
    "ResidualConstraintSpec",
    "ResidualSimulationResult",
    "ResidualTransitionSystem",
    "RunAvailabilityReport",
    "RunMode",
    "RunPackage",
    "SCHEMA_VERSION",
    "STABLE_DEFICIENCY_CODES",
    "StatisticalVerifierResult",
    "StatisticalVerifierPlugin",
    "SystemSpec",
    "TheoryAlignmentItem",
    "TheoryAlignmentReport",
    "TheoryImplementationStatus",
    "TypedMapSpec",
    "VerifierSpec",
    "availability_preorder",
    "almost_sure_available",
    "binomial_p_value",
    "bounded_reachability_probability",
    "bounded_residual_simulation",
    "coarse_availability_class",
    "continuation_readout",
    "continuation_preorder",
    "continuation_preorder_result",
    "default_theory_alignment_report",
    "deficiency_profile_key",
    "deficiency_code_info",
    "direct_selector_witness",
    "evaluate_run_modes",
    "evaluate_binomial_verifier",
    "find_factorization_witness",
    "greedy_repair_cover",
    "has_residual_simulation",
    "has_residual_scientific_space",
    "least_fixed_point",
    "one_step_residual_labels",
    "reachability_probability",
    "residual_includes",
    "residual_refinement_count",
    "residual_repair_count",
    "residual_test_count",
    "reproducibly_available_predicate",
    "schema_id",
    "solve_repair_cover",
    "solve_cascaded_repair",
    "solve_coherent_repair",
    "solve_continuation_repair",
    "solve_weighted_repair_cover",
    "wilson_score_interval",
]
